# Generated by Django 3.2.12 on 2022-11-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_dialog',
            field=models.BooleanField(default=False, verbose_name='Диалог'),
        ),
    ]
