# Generated by Django 3.2.12 on 2022-11-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_is_dialog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_dialog',
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название чата'),
        ),
    ]
