# Generated by Django 3.2.12 on 2022-11-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20221121_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание чата'),
        ),
    ]
