# Generated by Django 3.2.12 on 2022-11-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chat_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='editing_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования чата'),
        ),
    ]
