# Generated by Django 3.2.12 on 2022-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creating_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
    ]
