# Generated by Django 3.2.12 on 2022-11-13 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chats.chat', verbose_name='Чат'),
        ),
    ]
